@extends('front/front_layout')
@section('active')
<div class="collapse navbar-collapse" id="navbarNav">
 <ul class="navbar-nav">
     <li class="nav-item ">
         <a class="nav-link" href="/front-home">home </a>
     </li>
     <li class="nav-item">
         <a class="nav-link" href="/front-about-us">about us  <span class="sr-only">(current)</span></a>
     </li>
     <li class="nav-item">
         <a class="nav-link" href="#">articles</a>
     </li>
     <li class="nav-item">
         <a class="nav-link" href="/donation-requests">donation requests</a>
     </li>
     <li class="nav-item active">
         <a class="nav-link" href="/front-about-us">who are us</a>
     </li>
     <li class="nav-item">
         <a class="nav-link" href="/contact-us">contact us</a>
     </li>
 </ul>
 
 <!--not a member-->
 <div class="accounts">
     <a href="/signin-account" class="signin">sign in</a>
     <a href="/create-account" class="create">create new account</a>
 </div>
 
 <!--I'm a member

 <a href="#" class="donate">
     <img src="imgs/transfusion.svg">
     <p>طلب تبرع</p>
 </a>

 -->
 
</div>
@endsection
@section('content')
        <!--inside-article-->
        <div class="about-us">
            <div class="container">
                <div class="path">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index-ltr.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Who are us</li>
                        </ol>
                    </nav>
                </div>
                <div class="details">
                    <div class="logo">
                        <img src="imgs/logo-ltr.png">
                    </div>
                    <div class="text">
                        <p>
                            This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. Many other texts in addition to increasing the number of characters generated by the application.
                        </p>
                        <p>
                           This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. Many other texts in addition to increasing the number of characters generated by the application.
                        </p>
                        <p>
                            This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. Many other texts in addition to increasing the number of characters generated by the application.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        
        

        @endsection